### ISSUE TITLE
Some messages cannot be changed

### ISSUE THREAD

**Issue by 2580crq** [AlexProgrammerDE/PistonChat#17]
This is a great plug-in, but when I try to send a private chat message to myself, the pop-up message cannot be changed in the configuration file, please solve this problem, thank you.

**Comment by AlexProgrammerDE** [comment]
I will be adding a file called language.yml in the next update. You can set way more messages with it then.

**Comment by 2580crq** [comment]
> 我将在下一个更新中添加一个名为language.yml的文件。然后，您可以使用它来设置更多消息的方式。

thank you

**Comment by AlexProgrammerDE** [comment]
Can be edited in latest release.
