### ISSUE TITLE
Compile undefined

### ISSUE THREAD

**Issue by Roshanxy** [AlexProgrammerDE/PistonChat#34]
Hello I want to compile this plugin from source but I can't seem to fix these;
The constructor CacheTool(PistonChat) is undefined
	The constructor IgnoreTool(PistonChat) is undefined
	The constructor HardIgnoreCommand(PistonChat) is undefined
	The constructor HardIgnoreCommand(PistonChat) is undefined
	The constructor SoftIgnoreCommand(PistonChat) is undefined
	The constructor SoftIgnoreCommand(PistonChat) is undefined
	The constructor WhisperCommand(PistonChat) is undefined
	The constructor WhisperCommand(PistonChat) is undefined
	The constructor ReplyCommand(PistonChat) is undefined
	The constructor ReplyCommand(PistonChat) is undefined
	The constructor LastCommand(PistonChat) is undefined
	The constructor LastCommand(PistonChat) is undefined
	The constructor IgnoreListCommand(PistonChat) is undefined
	The constructor IgnoreListCommand(PistonChat) is undefined
	The constructor ToggleWhisperingCommand(PistonChat) is undefined
	The constructor ToggleWhisperingCommand(PistonChat) is undefined
	The constructor ToggleChatCommand(PistonChat) is undefined
	The constructor ToggleChatCommand(PistonChat) is undefined
	The constructor ChatEvent(PistonChat) is undefined

From the source file at release
Some older version from May worked lovely

**Comment by AlexProgrammerDE** [comment]
You may have issues with your maven setup. Next time please join my discord. Github actions works fine.
