### ISSUE TITLE
mariadb

### ISSUE THREAD

**Issue by f3f5-dev** [AlexProgrammerDE/PistonChat#90]
[ERROR] [org.mariadb.jdbc.pool.Pool] error initializing pool connection
java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused 

maybe make option to use mariadb? because i cant use plugin without mariadb

**Comment by AlexProgrammerDE** [comment]
MariaDB/MySQL is required for this plugin to work currently.

**Comment by f3f5-dev** [comment]
> MariaDB/MySQL is required for this plugin to work currently.

ok, no problem, it working :)
![image](https://github.com/AlexProgrammerDE/PistonChat/assets/137526883/d278e152-faef-4084-9906-fbe68181f704)
