### ISSUE TITLE
[Bug] Togglewhispering

### ISSUE THREAD

**Issue by ghost** [AlexProgrammerDE/PistonChat#92]
if you use the command Togglewhispering He's writing Private message unhidden. 
but normal: Private message hidden. 

for /togglechat it fixed

**Comment by AlexProgrammerDE** [comment]
Fixed: https://github.com/AlexProgrammerDE/PistonChat/commit/5b2ef57bb0e6c809ae9f3c78af1a49b3804d9dd0
